#!/usr/bin/env bash

# This is an example of how to implement a command which reads a
# couple of environment files and then delegates control to its
# subcommands in a `libexec' folder using `exec-longest-prefix'.

for envfile in ~/.fooenv .fooenv; do
  if [[ -f "$envfile" ]]; then
    while read line; do
      export "$line"
    done < "$envfile"
  fi
done

exec-longest-prefix "$0"/../../libexec "$@"
